export const REQUEST_API_DATA = "REQUEST_API_DATA";
export const RECEIVE_API_DATA = "RECEIVE_API_DATA";
export const PRODUCT_SEARCH_DATA = "PRODUCT_SEARCH_DATA";

export const GET_PRODICT_DATA = "GET_PRODICT_DATA";
export const PRODUCT_SUCCESS_DATA = "PRODUCT_SUCCESS_DATA";
export const PRODUCT_FAIL_DATA = "PRODUCT_FAIL_DATA";
export const SEARCH_PRODUCT_DATA = "SEARCH_PRODUCT_DATA";
